branches:
  only:
    - master

notifications:
  email: false

matrix:
  include:
    - &macos
      name: macOS / Swift 4.2
      language: objective-c
      osx_image: xcode10.1
      os: osx
      script: &macos_script
        - swift --version
        - make test/spm
        - make test/xcode
      after_success:
        - bash <(curl -s https://codecov.io/bash) -X gcov -J '^Tablier$'
    
    - <<: *macos
      name: macOS / Swift 5.0
      osx_image: xcode10.2
      script: *macos_script
      script:
        - make test/examples
        - swift test --generate-linuxmain
        - git diff --exit-code **/XCTestManifests.swift

    - name: Linux / Swift 5.0
      language: generic
      dist: xenial
      env: SWIFT_VERSION=5.0
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - make test/spm
