branches:
  only:
    - master

notifications:
  email: false

matrix:
  include:
    - name: macOS / Swift 4.2
      language: objective-c
      osx_image: xcode10.1
      os: osx
      script:
        - swift --version
        - make lint/xcode test/spm test/xcode
      after_success:
        - bash <(curl -s https://codecov.io/bash) -X gcov -J '^Tablier$'

    - name: macOS / Swift 5.0
      language: objective-c
      osx_image: xcode10.2
      os: osx
      script:
        - swift --version
        - make lint/xcode test/spm test/xcode
        - make linuxmain && git diff --exit-code **/XCTestManifests.swift
      after_success:
        - bash <(curl -s https://codecov.io/bash) -X gcov -J '^Tablier$'

    - name: Linux / Swift 5.0
      language: generic
      dist: xenial
      env: SWIFT_VERSION=5.0
      install:
        - git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
        - export SWIFTENV_ROOT="$HOME/.swiftenv"
        - export PATH="$SWIFTENV_ROOT/bin:$PATH"
        - eval "$(swiftenv init -)"
        - swiftenv install
      script:
        - swift --version
        - make test/spm
